pipeline {
    agent any

    environment {
        XRAY_CLIENT_ID     = "F2498B97E48E432B8CA9C60B2643F5FE"
        XRAY_CLIENT_SECRET = "00842304a949a62fb253162641daf2d466a7d12973a501542f69d7d63af17071"
    }

    parameters {
        string(name: 'SELENIUM_BROWSER', defaultValue: 'CHROME')
    }

    triggers {
        cron('00 10 * * 2')
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Download Features from Xray') {
            steps {
                echo 'Téléchargement des features depuis Xray...'

                // 1. Générer le token
                bat """
                    curl -H "Content-Type: application/json" ^
                         -X POST ^
                         -d "{\\"client_id\\": \\"%XRAY_CLIENT_ID%\\", \\"client_secret\\": \\"%XRAY_CLIENT_SECRET%\\"}" ^
                         https://xray.cloud.getxray.app/api/v2/authenticate ^
                         -o token.txt
                """

                // Lire le token
                bat 'set /p XRAY_TOKEN=<token.txt'

                // 2. Télécharger les features en ZIP
                bat """
                    curl -H "Authorization: Bearer %XRAY_TOKEN%" ^
                         -X GET ^
                         -o features.zip ^
                         "https://xray.cloud.getxray.app/api/v2/export/cucumber?keys=POEI2-972"
                """

                echo 'Dézip des features...'

                // 3. Dézipper dans un dossier temporaire
                bat """
                    powershell -Command "Expand-Archive -Force features.zip extracted_features"
                """

                echo 'Copie des features dans le projet...'

                // 4. Copier dans ton projet
                bat """
                    xcopy /Y /E /I extracted_features SauceLabCucumber\\src\\test\\resources\\features
                """
            }
        }

        stage('Build & Test') {
            steps {
                echo 'Execution des tests Cucumber via Maven...'
                bat 'cd SauceLabCucumber && mvn clean test'
            }
        }
    }

    post {
        always {
            echo 'Pipeline terminé'
        }
    }
}
